export {default as Navbar} from  './Navbar';
export {default as HeroSection} from './HeroSection';
export {default as Sales1} from './Sales1';
export {default as Sales2} from './Sales2';
export {default as Testimonials} from './Testimonials';
export {default as Footer} from './Footer'
export {default as Hero} from './Hero';
export {default as CartComponent} from './CartComponent';
export {default as Consideration} from './Consideration';
